### ISSUE TITLE
Can not bundle package using webpack 2

### ISSUE THREAD

**Issue by dpashin** [devote/HTML5-History-API#104]
# Can not bundle package using webpack 2

Hi.
Now i'm using html5-history-api and webpack 1.14.0, and all works fine.
I've tried to upgrade webpack to 2.x and got error "Uncaught ReferenceError: Invalid left-hand side in assignment"

Seems that webpack rewrites this code and something goes wrong.

    (function(factory) {
      if (typeof define === 'function' && define['amd']) {
        if (typeof requirejs !== 'undefined') {
          // https://github.com/devote/HTML5-History-API/issues/73
          var rndKey = '[history' + (new Date()).getTime() + ']';
          var onError = requirejs['onError'];
          factory.toString = function() {
            return rndKey;
          };
          requirejs['onError'] = function(err) {         // <==== ERROR HERE
            if (err.message.indexOf(rndKey) === -1) {
              onError.call(requirejs, err);
            }
          };
        }
        define([], factory);
      }

Steps to reproduce:
1. git clone git@github.com:dpashin/history-bug.git
2. npm i
3. node node_modules/webpack/bin/webpack.js
4. open index.html in browser and you will see error in console

**Comment by superartgun** [comment]
I am also getting this error after switching to webpack 2

**Comment by superartgun** [comment]
@dpashin You managed to solve the problem ?

**Comment by dpashin** [comment]
@superartgun, as a workaround, i can fork repo and remove this block   
`if (typeof requirejs !== 'undefined') {...} `

than all builds fine. 
Of course, it's a bad solution.
I'm waitng for an answer.

**Comment by devote** [comment]
Hello!

I have no way to check it out right now.

Tell me, what type of a variable requirejs at the time of the error?

**Comment by devote** [comment]
The necessary changes have been made. I apologize for the delay.

**Comment by dpashin** [comment]
@devote, did you published new version to npm registry? I don't see new version here https://www.npmjs.com/package/html5-history-api

**Comment by devote** [comment]
Sorry! Published!

**Comment by dpashin** [comment]
Thanks! all works.
