### ISSUE TITLE
Breaking Issue: Safari yields error "[Error] SyntaxError: Invalid character '\ufffd' 	(anonymous function)"

### ISSUE THREAD

**Issue by niftylettuce** [devote/HTML5-History-API#108]
Both Mobile Safari and Safari both have this issue.  The issue did not occur in v4.2.8.  However it does occur in v4.2.10.

<img width="300" alt="Screen Shot 2019-06-06 at 4 54 35 PM" src="https://user-images.githubusercontent.com/523141/59069138-ecfefe80-887b-11e9-9cee-c51dd52054cc.png">

**Comment by devote** [comment]
You can show me a more detailed error. I will be very grateful. Thanks!

**Comment by niftylettuce** [comment]
It wasn't this package, I filed wrong issue
