### ISSUE TITLE
pushState not working on Chrome on IOS 6 (ipad)

### ISSUE THREAD

**Issue by ThaNarie** [devote/HTML5-History-API#29]
When i do a pushState on Chome on ISO6, nothing happens. The native pushState does work (when not loading this library).

I'm trying to debug it myself, but hopefully you can fix it.

I'm having it currently on:
ipad 3 ios 6.0.1
ipad 3 ios 6.1.2
iphone 4 ios 6.1

**Comment by oleg-andreyev** [comment]
Ref. to source in CriOS (about override pushState/replaceState):
https://chromium.googlesource.com/chromium/src/+/master/ios/web/web_state/js/resources/core.js#412
https://chromium.googlesource.com/chromium/src/+/master/ios/web/web_state/js/resources/core.js#427
