### ISSUE TITLE
Ошибка при передачи параметров в history.redirect();

### ISSUE THREAD

**Issue by fobazzz** [devote/HTML5-History-API#35]
Если передовать параметры history.redirect('page=')  при загрузки страницы и после этого поменять hash страницы вручную в URL произойдет редирект на hash страницы.
Воспроизводится в Chrome, FF

**Comment by devote** [comment]
Возможно это уже не актуально, пожалуйста откройте этот вопрос или создайте новый если вопрос еще не исчерпан. Спасибо!
