### ISSUE TITLE
history.state in Safari not null

### ISSUE THREAD

**Issue by woelfchen** [devote/HTML5-History-API#45]
If I change the value in the address bar, then history.state never zero. 
In the other browser is the history.state zero.

If I use the back or forward button, then is history.state already filled in all browser.
That is okay.

**Comment by devote** [comment]
Please reopen it or create new issue if you needed. Thanks!

**Comment by warappa** [comment]
Version 4.2.1

I just encountered this issue with IE11. In Chrome (42 and earlier) and Firefox (38) it works as expected: new Url has no state assigned.

**Comment by devote** [comment]
I do not know how to reproduce this problem, you can give an example?
