### ISSUE TITLE
Multiple hashes IE9

### ISSUE THREAD

**Issue by Kreshnik** [devote/HTML5-History-API#55]
I have noticed one thing in IE9, after using the page for a while the hash will duplicate see image bellow;

![multiple-hashes](https://cloud.githubusercontent.com/assets/1788349/2970557/036b5b5e-db5d-11e3-9023-d6db40b223e5.png)

**Comment by devote** [comment]
Please reopen it or create new issue if you needed. Thanks!

**Comment by evilebottnawi** [comment]
@devote i got same error in IE9
On jQuery ready i use
```javascript
this.history.replaceState($.extend({
        doNotChangeState: false,
        url: window.location.href
    }, this.options),
    document.title,
    window.location.href
);
```
Add own settings to current state and window.location.href have hash (start url http://mydomain.com/#/hello-world-3/);
