### ISSUE TITLE
Anchor links for scrolling create a wrong url in IE9 and below which breaks the content.

### ISSUE THREAD

**Issue by danieljmg** [devote/HTML5-History-API#68]
A scroll link as \<a href="#idx"> doesnt work under IE9 and below after pushed some hashtag state.
Lets say, I'm on localhost/index, I go to "a" through ajax what push localhost/index#/a, and now inside "a" I click on \<a href="#idx"> that must scroll to #idx on a. When I press, it ask to the web server(nginx) for localhost/index#/idx rather than localhost/index#/a#idx.
For know I'll go to a javascript solution rather than html, but I think it's worth to make you know about this issue. Regards.

**Comment by devote** [comment]
Please reopen it or create new issue if you needed. Thanks!
