### ISSUE TITLE
Popstate event not firing when pressing Back/Forward button in IE8-IE9

### ISSUE THREAD

**Issue by GeraldIstar** [devote/HTML5-History-API#72]
Well, problem is described in title. I'm using .on() method. In Chrome with and without library all works OK. But in IE it's not triggering. Is threre some nicety may be?

**Comment by devote** [comment]
Hi,
jQuery version is?
Thanks!

**Comment by devote** [comment]
This [demo](http://docs.spb-piksel.ru/demos/history/) works correctly on the IE8-9

**Comment by GeraldIstar** [comment]
I'm using jQuery 1.11.1. I've change event attaching to native attachEvent method, and it works. Looks like problem with jQuery. Code is simple, I don't know where I might wrong.
`$(window).on('popstate', function(){ /* some code */ });`

**Comment by devote** [comment]
My test works fine [http://devote.github.io/tests/history/popstate.html](http://devote.github.io/tests/history/popstate.html) in IE11 with emulate IE8-9. Maybe I need to look for a machine with a built-in version of the browser IE8-9. I'll let you know when I find IE8-9 native

**Comment by devote** [comment]
I run my test using IE8 and IE9. Everything works fine!

**Comment by GeraldIstar** [comment]
I found that different builds/veriosn of IE8 behave different. Some version have bug, that is not in another version. I will check your lib in other build in next week.

**Comment by devote** [comment]
Ok. Please close this issue if your problem is successfuly resolved. Thanks!

**Comment by devote** [comment]
Please reopen it or create new issue if you needed. Thanks!
