### ISSUE TITLE
commonJS support?

### ISSUE THREAD

**Issue by vvo** [devote/HTML5-History-API#75]
Hi, could we have commonJS support? thx

**Comment by devote** [comment]
Hi
For polyfill need a browser. Why do you need a polyfill without a browser?

**Comment by vvo** [comment]
I mean something where I could do `var History = require('html5-history-api')` so that I do not overwrite the full window.history.

I am developing some code that should be able to be inserted in a lot of different website so I cannot just erase the full window.history.

**Comment by devote** [comment]
I do not quite understand. Can you describe in more detail your situation. Thank you!

**Comment by vvo** [comment]
I want to be able to require and use your library without it being inserted automatically in the global scope and replacing the original history object.

```js
var History = require('html5-history-api')
History.pushState();
History.on('popstate')

// etc..
```

**Comment by devote** [comment]
You want this library to fully simulate the History-API without a browser?

**Comment by flipchart** [comment]
CommonJS is used within the browser via toolchains like Browserify and Webpack. I believe this is how @vvo will use the library. So instead of providing the global `window.history.location`, you would be able to use the library via `var location = require("html5-history-api")`

**Comment by vvo** [comment]
Exactly what @flipchart said :-). Why do this? Because if you are a library author you do not want to pollute the original document by providing a polyfill in window.history while the website author may have some scripts expecting it not to exists.

**Comment by devote** [comment]
Added support CommonJS
