### ISSUE TITLE
License version confirm

### ISSUE THREAD

**Issue by PeterDaveHello** [devote/HTML5-History-API#79]
Hi there,

I just found that you used GPL in package.json:
https://github.com/devote/HTML5-History-API/blob/master/package.json#L32
```js
  "licenses": [
    "GPL",
    "MIT"
  ]
```

and GPL3 in bower.json
https://github.com/devote/HTML5-History-API/blob/master/bower.json#L22
```js
  "licenses": [{
    "type": "GPL3"
  }, {
```

Just wanna confirm that, so that we can show the correct license on cdnjs page:
https://cdnjs.com/libraries/html5-history-api

Thanks!

cc @maruilian11 @LeaYeh @Amomo @Piicksarn

**Comment by devote** [comment]
Hi,
The correct license is GPL 3 / MIT

**Comment by PeterDaveHello** [comment]
Thanks, I think it'll be better to use "GPL-3.0" in both bower.json/package.json :smile:

**Comment by devote** [comment]
Yes of course

**Comment by PeterDaveHello** [comment]
Nice
