### ISSUE TITLE
Out of stack space in IE8/9

### ISSUE THREAD

**Issue by eithed** [devote/HTML5-History-API#89]
Hello,

When using history.js with provided example code (https://github.com/devote/HTML5-History-API#example-of-using-the-library-in-the-pure-js-context) I'm getting SCRIPT28: Out of stack space (File: history.js, Line: 416, Column: 5) error.

Curiously enough, the minified version works.

**Comment by Naeemo** [comment]
I have the same problem, even worse: the minified version doesn't work either.

**Comment by devote** [comment]
Hi,
Can you give an example of code that will be played this error?

**Comment by galsas** [comment]
I made a pull request that solve the problem #91

Note: The error appear to me using angular 2 and this library as pollyfill for IE9

**Comment by Naeemo** [comment]
Thanks, all. ^ - ^
