### ISSUE TITLE
Licence Problem

### ISSUE THREAD

**Issue by mrJakez** [devote/HTML5-History-API#90]
Hi guys,

we want to use this library in a commercial product. Therefore our company had checked all licences of the third party products we want to use. And thereby we detected a problem with your licence wording.

Is it possible to change your licence to MIT only? Currently it seems that your lib is licensed under MIT AND GPL, and not MIT or GPL.

Cheers
Dennis

**Comment by devote** [comment]
Hi,
Yes of course you can use the library for commercial purposes, I have long been planning to use only the MIT license.

**Comment by mrJakez** [comment]
Hey,

many thanks for that quick reply! Sounds great - I'm also fine with creating a push request for you which changes the licence agreements to MIT only. That will reduce your effort and helps us a lot!:)

Is that  feasible for you?

Cheers

**Comment by devote** [comment]
I already made the necessary changes, but thanks anyway!

**Comment by mrJakez** [comment]
Many thanks - wonderful small world ;-)
