### ISSUE TITLE
Support for AMD loaders other than RequireJS

### ISSUE THREAD

**Issue by dchekanov** [devote/HTML5-History-API#92]
AMD modules can be loaded by a number of different loaders, for example by SystemJS via [jspm](http://jspm.io/). Currently HTML5-History-API won't work with them because it assumes that `requirejs` is available if `define` is a function (https://github.com/devote/HTML5-History-API/blob/master/history.js#L19). 

An additional simple check if `requirejs` is available should fix this.

**Comment by devote** [comment]
Yes, you right!
