### ISSUE TITLE
I want go "/test" link but "/#/test" in fact 

### ISSUE THREAD

**Issue by alonprince** [devote/HTML5-History-API#93]
When I use `history.pushState({foo: 'bar'}, 'test', '/test')` to replace href to `/test`, but it doesn't work well in IE8.It go to the `/#/test`.

**Comment by devote** [comment]
What result do you expect in IE8?

**Comment by alonprince** [comment]
For example, my `window.location.href` is `www.google.com/` now, when i use `history.pushState({foo: 'bar'}, 'test', '/test')`.I expect that I will get `www.google.com/test`,but I get `www.google.com/#/test`

**Comment by devote** [comment]
In IE 8-9 is the norm, because there is no other way to replace the URL in those browsers. Since they do not support natively History-API.

**Comment by alonprince** [comment]
I just searched the documents of Hashbang.Thank you for giving me a good lesson.
